version: 2.1
jobs:
  build: &shared-config
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          name: restore yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          name: restore yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn lint && yarn format:check
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          name: restore yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn test:ci
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  database:
    docker:
      - image: cimg/node:12.18
        environment:
          DATABASE_URL: "postgres://psuser:pspwd@localhost:5432/psdb"
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
          JWT_SECRET: something
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: psuser
          POSTGRES_DB: psdb
          POSTGRES_PASSWORD: pspwd
    steps:
      - checkout
      - restore cache:
          name: restore yarn package cache
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run:
          command: yarn test:e2e

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - database:
          requires:
            - build
