version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: yarn global add node-gyp && yarn install
      - restore_cache:
          keys:
          - npm-v1-dependencies-{{ checksum "yarn.lock" }}