version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
     
      - restore_cache:
          name: restore yarn package cache
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          name: sa  ve yarn package cache
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn